[package]
name = "FastLibPython"
version = "0.1.0"
authors = ["dark0ghost"]
edition = "2018"


[lib]
name = "fastpython"
crate-type = ["cdylib"]

[dependencies]
#cpython = "0.5.0"

[dependencies.cpython]
version = "0.5.0"
features = ["extension-module"]
